/*
 * Writes src/components/iconPaths.js: the drawing of each icon the notebook
 * uses, in the two weights it uses, taken from Phosphor Icons (MIT).
 *
 * The Phosphor React package ships all six weights of every icon it exports,
 * so each icon cost the bundle about 2.4 kB; the notebook needs only regular
 * and bold. To add an icon, add it to ICONS below (the key is the app's name
 * for it, the value Phosphor's) and run `npm run icons`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const ICONS = {
  "arrow-up-right": "ArrowUpRight",
  "book-open": "BookOpen",
  calendar: "CalendarBlank",
  chart: "ChartBar",
  check: "Check",
  chevron: "CaretDown",
  "chevron-right": "CaretRight",
  clock: "Clock",
  edit: "PencilSimple",
  eye: "Eye",
  flame: "Fire",
  frown: "SmileySad",
  globe: "Globe",
  help: "Question",
  moon: "Moon",
  more: "DotsThree",
  plus: "Plus",
  "rotate-ccw": "ArrowCounterClockwise",
  search: "MagnifyingGlass",
  sliders: "SlidersHorizontal",
  smile: "Smiley",
  sort: "ArrowsDownUp",
  sparkles: "Sparkle",
  star: "Star",
  sun: "Sun",
  target: "Target",
  trash: "Trash",
  volume: "SpeakerHigh",
  x: "X",
};
const WEIGHTS = ["regular", "bold"];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const defs = path.join(root, "node_modules/@phosphor-icons/react/dist/defs");

// A weight's drawing: the outline of each of its paths. Phosphor draws the
// regular and bold weights with filled paths only; anything else is refused
// rather than silently dropped.
function outlines(node) {
  if (node == null || typeof node === "boolean") {
    return [];
  }

  if (Array.isArray(node)) {
    return node.flatMap(outlines);
  }

  const { children, ...attributes } = node.props ?? {};

  if (typeof node.type !== "string") {
    return outlines(children);
  }

  if (node.type !== "path" || Object.keys(attributes).join() !== "d") {
    throw new Error(`Unexpected <${node.type}> ${JSON.stringify(attributes)}`);
  }

  return [attributes.d];
}

const paths = {};

for (const [name, phosphor] of Object.entries(ICONS)) {
  const { default: weights } = await import(pathToFileURL(path.join(defs, `${phosphor}.es.js`)).href);
  paths[name] = Object.fromEntries(WEIGHTS.map((weight) => [weight, outlines(weights.get(weight))]));
}

const source = `// Generated by scripts/build-icons.mjs from Phosphor Icons (MIT,
// https://phosphoricons.com). Run \`npm run icons\` after changing the list
// there; don't edit this file by hand.
export default ${JSON.stringify(paths)};
`;

writeFileSync(path.join(root, "src/components/iconPaths.js"), source);
console.log(`Wrote ${Object.keys(paths).length} icons in ${WEIGHTS.join(" and ")}.`);
